services:
  - type: web
    name: cre-valuate-pro-backend
    env: node
    repo: https://github.com/mariolucky82/cre-valuate-pro
    branch: chore/vercel-deploy-setup
    plan: standard
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars: []
    autoDeploy: true
    regions:
      - oregon
    disk: 0
    cpu: "1"
    memory: "1GB"
